server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: SoftConEx
  datasource:
    url: jdbc:mysql://localhost:3306/softcon_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.softcon.entity
  configuration:
    map-underscore-to-camel-case: true

